### ISSUE TITLE
Make a calculator using HTML/CSS/JAVASCRIPT

### ISSUE THREAD

**Issue by ashisdey12** [ashisdey12/FULLDEV#2]
Make a separate folder for Calculator

**Comment by agarwalBinay18** [comment]
can you assign me this?

**Comment by pooja-gera** [comment]
Hi, can you assign this issue to me?

**Comment by kushdeepwalia** [comment]
Hi, Can you assign this issue to me? I have the code ready with me

**Comment by zippytyro** [comment]
Hey, can you assign me this one?

**Comment by ashisdey12** [comment]
@kushdeepwalia @zippytyro it's great but I have to assignee on the first-come-first-serve basis. You can raise the issue and I will be merging the PR. But Be sure that the issue you are creating is some development Project.

**Comment by kushdeepwalia** [comment]
> @kushdeepwalia @zippytyro it's great but I have to assignee on the first-come-first-serve basis. You can raise the issue and I will be merging the PR. But Be sure that the issue you are creating is some development Project.

I have made PR. Uploaded the files of the calculator in it.

**Comment by pooja-gera** [comment]
Hi @ashisdey12 thanks for assigning, I'll create a PR before 5am tomorrow and ensure that the UI of the calculator is also taken into consideration. 
Best Regards 
Pooja Gera
